name: Sahan Portfolio
on:
  push:
    branches:
      - "dev-sahan"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get the Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Run the Project
        run: echo "App Running"
      - name: Deploy
        run: echo "App Working Without Any Issue"
