name: Sahan Portfolio
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get the Code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm ci
      - name: Run the Project
        run: npm start
      - name: Deploy
        run: echo "App Working Without Any Issue"