name: Delta
on:
  push:
    - master
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Start
        run: echo "This is a push to the main branch"
      - name: Cloning the code
        uses: actions/checkout@v4
      - name: Listing Files
        run: ls -l
      - name: Install Dependencies
        run: npm ci